/* triggerui.js — the shared trigger builder: WhenToTest, conditions, effects

   Part of the Medieval 2 GUI Toolkit UI. These files are plain
   <script> tags sharing ONE global scope, loaded in the order set in
   index.html — there is no build step and no module system. Two rules
   follow from that: a top-level name must be unique across all of
   them, and a file's top-level side effects may not depend on a file
   loaded after it.

   ======================= TRIGGER BUILDER =======================
   Traits, ancillaries and (later) the guild and faction-standing files all end
   in the same construct, so it gets one builder, built once — the same bargain
   as Code View. Its hosts are the Traits editor (Phase 8b) and the Ancillaries
   editor (Phase 9); it is here first because both of them need it and neither
   should own it.

   A host supplies:
     mod        which mod's names fill the operand pickers
     trigger    {name, when_to_test, conditions:[{term,args,joiner,negated}],
                 effects:[{keyword,args}]} — the same shape the save request and
                `codeview.render` use, so the builder, the text pane and the save
                cannot disagree about what a trigger is
     onChange(tr)  called after every edit, with the builder
     readOnly   optional

   THE PAGE NEVER PARSES A GAME FILE. The vocabulary arrives from
   /api/triggers/vocab as data — 413 conditions and 217 events generated by
   tools/trigger_vocab.py from the Docudemons spreadsheet and from every trigger
   file on the machine. What the builder does with it is set membership, not
   parsing: a condition names the data types it needs, an event names the types
   it exports, and a requirement no export satisfies is a trigger that will never
   fire. That warning is the one thing here you cannot get by reading the file,
   and it is why the vocabulary carries `requires` and `exports` at all.

   Their conditionDefs.jsx is NOT the source: 58 of its 78 conditions and 41 of
   its 82 events do not exist in the engine (merge/audit-trigger-vocab.md). */

// mod name -> vocabulary payload. One fetch per mod per session; the engine half
// is identical for every mod and the mod half is three cheap parses.
const TRG_VOCAB = {};
let TRG_SEQ = 0;
const TRG_LIVE = {};
const trgOf = uid => TRG_LIVE[uid];

function trgCreate(o){
  TRG_SEQ += 1;
  const t = o.trigger || {};
  const tr = {uid:'trg'+TRG_SEQ, host:o, mod:o.mod,
    name:t.name||'', when:t.when_to_test||'',
    conds:(t.conditions||[]).map(c=>({term:c.term||'', args:(c.args||[]).slice(),
      joiner:c.joiner||'', negated:!!c.negated})),
    effects:(t.effects||[]).map(e=>({keyword:e.keyword||'', args:(e.args||[]).slice()})),
    vocab:null, readOnly:!!o.readOnly};
  TRG_LIVE[tr.uid] = tr;
  return tr;
}
function trgDrop(tr){ if(tr) delete TRG_LIVE[tr.uid]; }

async function trgLoad(tr){
  const key = tr.mod || '';
  if(!TRG_VOCAB[key]){
    try{ TRG_VOCAB[key] = await api.get('/api/triggers/vocab?mod='+enc(key)); }
    catch(e){ TRG_VOCAB[key] = {error:''+e, conditions:[], events:[], operands:{}}; }
  }
  tr.vocab = TRG_VOCAB[key];
  tr.byTerm = {}; (tr.vocab.conditions||[]).forEach(c=>tr.byTerm[c.term]=c);
  tr.byEvent = {}; (tr.vocab.events||[]).forEach(e=>tr.byEvent[e.event]=e);
  return tr;
}

/* The value to save — exactly the shape the host was given, so a host can hand
   it straight to its plan/apply body and to codeview.render. */
function trgValue(tr){
  return {name:tr.name, when_to_test:tr.when,
    conditions:tr.conds.filter(c=>c.term).map((c,i)=>({term:c.term,
      args:c.args.filter(a=>a!==''), joiner:i===0?'':(c.joiner||'and'),
      negated:!!c.negated})),
    effects:tr.effects.map(e=>({keyword:e.keyword, args:e.args.slice()}))};
}

/* ---- what an event can and cannot answer ----
   `requires` is alternative groups: [[a,b],[c]] means (a and b) or c. A group
   fully covered by the event's exports is enough. */
function trgSatisfied(requires, exports){
  if(!requires || !requires.length) return true;
  const have = new Set(exports||[]);
  return requires.some(g => g.every(t => have.has(t)));
}
function trgCondWarn(tr, cond){
  const d = tr.byTerm[cond.term];
  if(!d) return cond.term ? `“${cond.term}” isn’t a condition anything documents — it may still be valid` : '';
  const ev = tr.byEvent[tr.when];
  if(!tr.when || !ev) return '';
  if(trgSatisfied(d.requires, ev.exports)) return '';
  const need = (d.requires||[]).map(g=>g.join(' and ')).join(', or ');
  return `needs ${need}, which ${tr.when} does not export — this can never be true`;
}

/* ---- markup ---- */
function trgHtml(tr){
  if(!tr.vocab) return '<div class="count">Loading the trigger vocabulary…</div>';
  if(tr.vocab.error) return `<div class="w-bad">✗ ${esc(tr.vocab.error)}</div>`;
  const ev = tr.byEvent[tr.when];
  return `<div class="trg" id="trg-${tr.uid}">
    <div class="trgrow">
      <span class="lbl">Trigger</span>
      <input id="trgname-${tr.uid}" value="${esc(tr.name)}" placeholder="name"
        oninput="trgSet(trgOf('${tr.uid}'),'name',this.value)" ${tr.readOnly?'disabled':''}>
      <span class="lbl">WhenToTest</span>
      ${trgEventSelect(tr)}
    </div>
    <div class="trghint">${ev
      ? `${esc(ev.hint||'')} <span class="count">· exports ${
          (ev.exports||[]).map(esc).join(', ')||'nothing'}</span>`
      : (tr.when?`<span class="w-bad">no engine event is called “${esc(tr.when)}”</span>`
               :'<span class="count">pick the moment this trigger is tested</span>')}</div>
    <div class="trgconds" id="trgc-${tr.uid}">
      ${tr.conds.map((c,i)=>trgCondHtml(tr,c,i)).join('')
        || '<div class="count">No conditions — this fires every time the event happens.</div>'}
    </div>
    ${tr.readOnly?'':`<button class="trgadd" onclick="trgAddCond(trgOf('${tr.uid}'))">
      ＋ Add condition</button>`}
    ${tr.effects.length?`<div class="trgeffects">${
      tr.effects.map((e,i)=>trgEffectHtml(tr,e,i)).join('')}</div>`:''}
  </div>`;
}

// Events, commonest in this mod's own files first: a list of 217 sorted A→Z buries
// the six anybody actually uses.
function trgEventSelect(tr){
  const evs = (tr.vocab.events||[]).slice().sort((a,b)=>
    (b.uses-a.uses) || a.event.localeCompare(b.event));
  const used = evs.filter(e=>e.uses>0), rest = evs.filter(e=>!e.uses)
    .sort((a,b)=>a.event.localeCompare(b.event));
  const opt = e=>`<option value="${esc(e.event)}" ${e.event===tr.when?'selected':''}>${
    esc(e.event)}${e.uses?` (${e.uses})`:''}</option>`;
  const unknown = tr.when && !tr.byEvent[tr.when]
    ? `<option value="${esc(tr.when)}" selected>${esc(tr.when)} — unknown</option>` : '';
  return `<select id="trgev-${tr.uid}" ${tr.readOnly?'disabled':''}
      onchange="trgSet(trgOf('${tr.uid}'),'when',this.value)">
    ${unknown}
    <optgroup label="used in this mod">${used.map(opt).join('')}</optgroup>
    <optgroup label="every other engine event">${rest.map(opt).join('')}</optgroup>
  </select>`;
}

function trgCondHtml(tr, cond, i){
  const d = tr.byTerm[cond.term];
  const warn = trgCondWarn(tr, cond);
  const shape = (d && d.shapes && d.shapes[0]) || '';
  return `<div class="trgcond${warn?' bad':''}" data-i="${i}">
    ${i===0?'<span class="jn">Condition</span>'
      :`<select class="jn" ${tr.readOnly?'disabled':''}
          onchange="trgSet(trgOf('${tr.uid}'),'joiner',this.value,${i})">
        <option ${cond.joiner!=='or'?'selected':''}>and</option>
        <option ${cond.joiner==='or'?'selected':''}>or</option></select>`}
    <label class="chk" title="Invert this clause"><input type="checkbox"
      ${cond.negated?'checked':''} ${tr.readOnly?'disabled':''}
      onchange="trgSet(trgOf('${tr.uid}'),'negated',this.checked,${i})">not</label>
    ${trgTermSelect(tr, cond, i)}
    <span class="trgargs">${trgArgsHtml(tr, cond, i, shape)}</span>
    ${tr.readOnly?'':`<button class="trgdel" title="Remove this clause"
      onclick="trgDelCond(trgOf('${tr.uid}'),${i})">✕</button>`}
    ${warn?`<div class="trgwarn w-bad">${esc(warn)}</div>`
      :(d&&d.hint?`<div class="trgwarn count">${esc(d.hint)}</div>`:'')}
  </div>`;
}

function trgTermSelect(tr, cond, i){
  const list = (tr.vocab.conditions||[]).slice().sort((a,b)=>
    (b.uses-a.uses) || a.term.localeCompare(b.term));
  const used = list.filter(c=>c.uses>0), rest = list.filter(c=>!c.uses)
    .sort((a,b)=>a.term.localeCompare(b.term));
  const opt = c=>`<option value="${esc(c.term)}" ${c.term===cond.term?'selected':''}>${
    esc(c.term)}${c.uses?` (${c.uses})`:''}</option>`;
  const unknown = cond.term && !tr.byTerm[cond.term]
    ? `<option value="${esc(cond.term)}" selected>${esc(cond.term)} — unknown</option>` : '';
  return `<select class="trgterm" ${tr.readOnly?'disabled':''}
      onchange="trgSet(trgOf('${tr.uid}'),'term',this.value,${i})">
    ${unknown}${cond.term?'':'<option value="" selected>— pick a condition —</option>'}
    <optgroup label="used in this mod">${used.map(opt).join('')}</optgroup>
    <optgroup label="every other engine condition">${rest.map(opt).join('')}</optgroup>
  </select>`;
}

/* One box per token of the term's shape. `op` is a picker, `num` a number, and
   `name` a text box backed by whatever list that term names — this mod's traits
   for `Trait`, its factions for `FactionType`, and so on. */
function trgArgsHtml(tr, cond, i, shape){
  const parts = (shape||'').split(' ').filter(Boolean);
  const src = (tr.vocab.operand_sources||{})[cond.term] || '';
  const list = (tr.vocab.operands||{})[src] || [];
  const ops = tr.vocab.operators || ['>=','<=','=','>','<'];
  // an argument the shape did not expect is still shown: a mod may write a form
  // no installed file happens to use, and hiding it would silently drop it
  const n = Math.max(parts.length, cond.args.length);
  let html = '';
  for(let k=0;k<n;k++){
    const kind = parts[k] || (cond.args[k] && ops.indexOf(cond.args[k])>=0 ? 'op' : 'name');
    const v = cond.args[k]===undefined?'':cond.args[k];
    const set = `trgSetArg(trgOf('${tr.uid}'),${i},${k},this.value)`;
    if(kind==='op'){
      html += `<select class="trgop" ${tr.readOnly?'disabled':''} onchange="${set}">${
        ops.map(o=>`<option ${o===v?'selected':''}>${esc(o)}</option>`).join('')}</select>`;
    }else if(kind==='num'){
      html += `<input class="trgnum" type="number" step="any" value="${esc(v)}"
        ${tr.readOnly?'disabled':''} oninput="${set}">`;
    }else{
      const dl = list.length?`trgdl-${tr.uid}-${src}`:'';
      html += `<input class="trgname" value="${esc(v)}" ${dl?`list="${dl}"`:''}
        placeholder="${esc(src||'value')}" ${tr.readOnly?'disabled':''} oninput="${set}">`;
      if(dl && html.indexOf('<datalist id="'+dl)<0)
        html += `<datalist id="${dl}">${list.map(x=>`<option value="${esc(x)}">`).join('')}</datalist>`;
    }
  }
  return html || '<span class="count">no argument</span>';
}

function trgEffectHtml(tr, eff, i){
  return `<div class="trgeff">
    <span class="lbl">${esc(eff.keyword)}</span>
    <input value="${esc(eff.args.join(' '))}" ${tr.readOnly?'disabled':''}
      oninput="trgSetEffect(trgOf('${tr.uid}'),${i},this.value)"></div>`;
}

/* ---- edits ----
   State first, paint second — the same rule the voice editor learned the hard
   way. A change that alters the SHAPE of the form repaints; typing in a box does
   not, or the caret would jump out from under the user on every keystroke. */
function trgSet(tr, key, value, i){
  if(key==='name'){ tr.name=value; return trgChanged(tr,false); }
  if(key==='when'){ tr.when=value; return trgChanged(tr,true); }
  const c = tr.conds[i]; if(!c) return;
  if(key==='term'){
    c.term=value;
    // a different condition takes different operands; keep what still fits
    const shape=((tr.byTerm[value]||{}).shapes||[''])[0].split(' ').filter(Boolean);
    c.args=shape.map((k,n)=>k==='op'?(c.args[n]&&tr.vocab.operators.indexOf(c.args[n])>=0?c.args[n]:'>=')
      :(c.args[n]||''));
    return trgChanged(tr,true);
  }
  if(key==='joiner'){ c.joiner=value; return trgChanged(tr,false); }
  if(key==='negated'){ c.negated=!!value; return trgChanged(tr,false); }
}
function trgSetArg(tr, i, k, value){
  const c = tr.conds[i]; if(!c) return;
  while(c.args.length<=k) c.args.push('');
  c.args[k]=value;
  trgChanged(tr,false);
}
function trgSetEffect(tr, i, value){
  const e = tr.effects[i]; if(!e) return;
  e.args = value.split(/\s+/).filter(Boolean);
  trgChanged(tr,false);
}
function trgAddCond(tr){
  tr.conds.push({term:'', args:[], joiner:tr.conds.length?'and':'', negated:false});
  trgChanged(tr,true);
}
function trgDelCond(tr, i){
  tr.conds.splice(i,1);
  if(tr.conds.length) tr.conds[0].joiner='';
  trgChanged(tr,true);
}
function trgChanged(tr, repaint){
  if(repaint) trgRepaint(tr);
  else trgPaintWarnings(tr);
  if(tr.host.onChange) tr.host.onChange(tr);
}
function trgRepaint(tr){
  const el = document.getElementById('trg-'+tr.uid);
  if(el) el.outerHTML = trgHtml(tr);
}
// Changing the event changes which clauses can ever be true, so the warnings are
// repainted on their own — without rebuilding the boxes being typed into.
function trgPaintWarnings(tr){
  const box = document.getElementById('trgc-'+tr.uid);
  if(!box) return;
  box.querySelectorAll('.trgcond').forEach(row=>{
    const c = tr.conds[+row.dataset.i]; if(!c) return;
    const warn = trgCondWarn(tr, c);
    row.classList.toggle('bad', !!warn);
    const w = row.querySelector('.trgwarn');
    if(w){ w.className = 'trgwarn ' + (warn?'w-bad':'count');
           w.textContent = warn || ((tr.byTerm[c.term]||{}).hint || ''); }
  });
}
