"""Medieval 2 GUI Toolkit — edit Medieval II: Total War mods.

Package layout:
  modeldb.py       parse/write data/unit_models/battle_models.modeldb (length-prefixed archive)
  edu.py           parse/write data/export_descr_unit.txt (unit stat blocks)
  eop.py           M2TWEOP units: the same EDU blocks, kept in the extender's own
                   files — discovery, parsing, and routing writes back to them
  luascan.py       what the mod's .lua scripts name, so the modeldb cleanup never
                   removes a battle model an M2TWEOP script still uses
  localization.py  parse/write data/text/export_units.txt (UTF-16 name/descr records)
  stringsbin.py    read/write the compiled data/text/*.txt.strings.bin archives —
                   the files the game ACTUALLY reads its text from
  strings.py       Strings mode: browse and edit those archives, and recompile one
                   from the .txt beside it
  cleaner.py       keep the compiled export_units.txt.strings.bin in step after a
                   job — rebuilt from the .txt where it can be, deleted otherwise
  triggers.py      the Trigger / WhenToTest / Condition / Affects language shared
                   by traits, ancillaries and the guild files — one grammar, one
                   serialiser, and a vocabulary that is DATA (data/trigger_vocab.json,
                   generated by tools/trigger_vocab.py) rather than code
  modfiles.py      what one mod has on disk per module — the Home page's matrix
  mod.py           Mod abstraction: paths, faction discovery, lazy DB access
  transfer.py      dependency resolution + cross-mod transfer (Stage 3)
  edit.py          unit EDITOR mode: change/create/delete units inside one mod
  bmdb.py          BMDB mode: the whole modeldb — browse/edit any entry, audit what
                   nothing references, and export the dead weight out of the mod
  pack.py          unit packs: units in a zip for someone else's machine. A pack
                   IS a mod, so importing one is an ordinary transfer out of it
  images.py        replacing any picture the UI shows: an `/icon` or
                   `/building_icon` URL back to the file on disk, where a
                   replacement goes, and the resolution check before it is written
  mesh.py          decode a battle model (.mesh) to geometry the viewer can draw
                   — a boost::serialization archive, reverse-engineered from the
                   files themselves because nothing we hold documents it
  server.py        local web UI (Stage 2)

Design rule: transfers APPEND verbatim source entries to the destination rather than
re-serializing whole destination files, so untouched entries are never reformatted.

Second design rule: a mod's roster is ``mod.edu.units`` — EDU units and M2TWEOP
units together — so every feature is EOP-aware by default. Only the *write* side
distinguishes them, via :func:`unittransfer.eop.compose`.
"""

__version__ = "2.1.0"
