"""The ``Trigger / WhenToTest / Condition / Affects`` language, parsed once.

Traits (``export_descr_character_traits.txt``), ancillaries
(``export_descr_ancillaries.txt``) and later the guild and faction-standing files
all end with the same construct::

    Trigger reputation_good_up1
      WhenToTest PostBattle
      Condition IsGeneral
             and Trait Gandalf > 0
             and not WonBattle
             and BattleOdds >= 1

      Affects Reputation_Good 1 Chance 100

One grammar, one parser, one serialiser — this module — so the traits editor and
the ancillaries editor cannot drift into disagreeing about what a condition
means. What each *term* means is not in here: it is data, generated by
``tools/trigger_vocab.py`` into ``unittransfer/data/trigger_vocab.json`` from the
Docudemons spreadsheet and from every trigger file on the machine. The engine's
vocabulary is the engine's business, not ours.

Three decisions worth knowing:

**Lines are kept verbatim and edits are splices.** These files are hand-written,
full of comment banners, mixed tabs and spaces, and blank lines inside condition
blocks. A re-emitting parser would reformat 10 000 lines to change one, so
``parse_text(t).text() == t`` for every file, always — that is the first thing
the tests check.

**An unknown term is a warning, never a loss.** Mods invent conditions, M2TWEOP
adds them, and the Docudemons list is a community effort rather than a spec. A
term nobody has documented still parses, still round-trips, and is reported so
the UI can say "this one I don't know" instead of quietly dropping the line.

**A condition can be wrong even when it parses.** Every event exports certain
data types and every condition requires certain ones — ``WonBattle`` needs a
``character_record``, which ``SettlementTurnStart`` does not export. That pairing
is in the vocabulary, so :func:`check` can say a trigger will never fire, which
is the failure mode nobody can see by reading the file.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path

from . import keyblock as kb
from typing import Dict, List, Optional, Tuple

#: EDCT and EDA are plain 8-bit text; the game reads them as Latin-1
ENCODING = "latin-1"

#: comparison tokens, longest first so ``>=`` never lexes as ``>``
OPS = ("<=", ">=", "!=", "==", "<", ">", "=")

#: the keyword that opens a trigger, and the ones that close the trigger section
TRIGGER_KW = "Trigger"
BLOCK_ENDERS = ("Trait", "Ancillary", "Guild", "Faction")

#: how a condition clause may be joined to the one before it
JOINERS = ("and", "or")

_VOCAB_PATH = Path(__file__).resolve().parent / "data" / "trigger_vocab.json"


class TriggerError(Exception):
    """The text is not a trigger block (with a line number, where known)."""

    def __init__(self, message: str, line: int = 0):
        super().__init__(message)
        self.message = message
        self.line = line


# ---------------------------------------------------------------------------
# the vocabulary (data, not code — see the module docstring)


@lru_cache(maxsize=1)
def vocab() -> Dict:
    """The generated vocabulary. Empty-but-usable if the file is missing."""
    try:
        raw = json.loads(_VOCAB_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {"conditions": [], "events": [], "attributes": [], "operators": list(OPS),
                "by_term": {}, "by_event": {}, "missing": True}
    raw["by_term"] = {c["term"]: c for c in raw.get("conditions", [])}
    raw["by_event"] = {e["event"]: e for e in raw.get("events", [])}
    return raw


def term_def(term: str) -> Optional[Dict]:
    return vocab()["by_term"].get(term)


def event_def(event: str) -> Optional[Dict]:
    return vocab()["by_event"].get(event)


# ---------------------------------------------------------------------------
# the parsed shapes


@dataclass
class Condition:
    """One clause of a ``Condition`` block."""
    term: str = ""
    args: List[str] = field(default_factory=list)
    joiner: str = ""            # '' for the first clause, else 'and' / 'or'
    negated: bool = False
    line: int = 0               # 0-based, into the file's lines
    raw: str = ""               # the line exactly as written, comment and all

    @property
    def shape(self) -> str:
        """``"name op num"`` — what boxes the GUI should draw for this clause."""
        out = []
        for a in self.args:
            out.append("op" if a in OPS else ("num" if _is_num(a) else "name"))
        return " ".join(out)

    def text(self, indent: str = "") -> str:
        """Re-emit this clause. Used when a clause is edited or added."""
        head = f"{self.joiner} " if self.joiner else ""
        neg = "not " if self.negated else ""
        return f"{indent}{head}{neg}{self.term}" + (
            " " + " ".join(self.args) if self.args else "")

    def as_dict(self) -> Dict:
        d = term_def(self.term)
        return {"term": self.term, "args": list(self.args), "joiner": self.joiner,
                "negated": self.negated, "line": self.line, "shape": self.shape,
                "known": d is not None,
                "hint": (d or {}).get("hint", ""),
                "requires": (d or {}).get("requires", [])}


@dataclass
class Effect:
    """A line after the condition block: ``Affects X 1 Chance 100`` and friends."""
    keyword: str = ""
    args: List[str] = field(default_factory=list)
    line: int = 0
    raw: str = ""

    def as_dict(self) -> Dict:
        return {"keyword": self.keyword, "args": list(self.args), "line": self.line}


@dataclass
class Trigger:
    name: str = ""
    when_to_test: str = ""
    conditions: List[Condition] = field(default_factory=list)
    effects: List[Effect] = field(default_factory=list)
    start: int = 0              # 0-based line of the `Trigger` line
    end: int = 0                # 0-based line AFTER the block's last line
    wtt_line: int = -1
    warnings: List[str] = field(default_factory=list)

    def as_dict(self) -> Dict:
        return {"name": self.name, "when_to_test": self.when_to_test,
                "start": self.start, "end": self.end,
                "conditions": [c.as_dict() for c in self.conditions],
                "effects": [e.as_dict() for e in self.effects],
                "warnings": list(self.warnings)}


@dataclass
class TriggerFile:
    """A whole EDCT/EDA, held as its own lines with the triggers indexed into it."""
    lines: List[str] = field(default_factory=list)
    newline: str = "\r\n"
    triggers: List[Trigger] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    trailing_newline: bool = True
    #: names of the definition blocks above the trigger section, by keyword —
    #: ``{"Trait": [...], "Ancillary": [...]}``. Collected on the same pass that
    #: has to recognise those lines anyway, so that the operand pickers can offer
    #: "which traits does THIS mod have" without a second parser. The blocks
    #: themselves belong to Phases 8 and 9.
    definitions: Dict[str, List[str]] = field(default_factory=dict)

    def text(self) -> str:
        """The file exactly as it was read — the property everything else rests on."""
        out = self.newline.join(self.lines)
        return out + self.newline if self.trailing_newline and self.lines else out

    def get(self, name: str) -> Optional[Trigger]:
        return next((t for t in self.triggers if t.name == name), None)

    def by_name(self) -> Dict[str, Trigger]:
        return {t.name: t for t in self.triggers}

    def block_text(self, trig: Trigger) -> str:
        return self.newline.join(self.lines[trig.start:trig.end])


# ---------------------------------------------------------------------------
# parsing


def _is_num(t: str) -> bool:
    try:
        float(t)
        return True
    except ValueError:
        return False


def _strip_comment(line: str) -> str:
    """The code part of a line. ``;`` starts a comment anywhere it appears."""
    return line.split(";", 1)[0]


def split_lines(text: str) -> Tuple[List[str], str, bool]:
    """``(lines, newline, had_trailing_newline)`` — how these files are split, once.

    Both halves of an EDCT are read by this: the trigger section here and the
    trait definitions in :mod:`unittransfer.traits`. Two copies of this would be
    two chances for one of them to disagree with the other about what line 4 is,
    in a file where every save is a line splice.
    """
    newline = "\r\n" if "\r\n" in text else "\n"
    body = text
    trailing = body.endswith("\n")
    if trailing:
        body = body[: -len(newline)] if body.endswith(newline) else body[:-1]
    lines = body.split("\n")
    return [ln[:-1] if ln.endswith("\r") else ln for ln in lines], newline, trailing


def parse_text(text: str) -> TriggerFile:
    """Read a whole trigger-bearing file. Never raises: bad lines become warnings.

    Only the *trigger section* is interpreted. Everything above it (the trait and
    ancillary definitions, which Phases 8 and 9 own) is carried as lines.
    """
    lines, newline, trailing = split_lines(text)

    tf = TriggerFile(lines=lines, newline=newline, trailing_newline=trailing)
    cur: Optional[Trigger] = None
    for i, raw in enumerate(lines):
        code = _strip_comment(raw).strip()
        if not code:
            continue
        words = code.split()
        head = words[0]
        if head == TRIGGER_KW:
            if cur is not None:
                cur.end = i
            cur = Trigger(name=words[1] if len(words) > 1 else "", start=i, end=i + 1)
            if not cur.name:
                cur.warnings.append(f"line {i + 1}: this Trigger has no name")
            tf.triggers.append(cur)
            continue
        if head in BLOCK_ENDERS:
            # a trait/ancillary definition — the trigger section has not started,
            # or (in a file that interleaves them) this one has ended
            if len(words) > 1:
                tf.definitions.setdefault(head, []).append(words[1])
            if cur is not None:
                cur.end = i
                cur = None
            continue
        if cur is None:
            continue
        cur.end = i + 1
        if head == "WhenToTest":
            cur.when_to_test = words[1] if len(words) > 1 else ""
            cur.wtt_line = i
            if not cur.when_to_test:
                cur.warnings.append(f"line {i + 1}: WhenToTest names no event")
            continue
        if head == "Condition" or head in JOINERS:
            cond = _parse_clause(words, i, raw, joiner="" if head == "Condition" else head)
            if cond is None:
                cur.warnings.append(f"line {i + 1}: {head} with nothing after it")
                continue
            cur.conditions.append(cond)
            continue
        cur.effects.append(Effect(keyword=head, args=words[1:], line=i, raw=raw))

    if cur is not None and cur.end < len(lines):
        cur.end = min(cur.end, len(lines))
    for t in tf.triggers:
        tf.warnings.extend(f"{t.name or '(unnamed)'}: {w}" for w in t.warnings)
    return tf


def _parse_clause(words: List[str], line: int, raw: str,
                  joiner: str) -> Optional[Condition]:
    rest = words[1:]
    negated = False
    if rest and rest[0] == "not":
        negated = True
        rest = rest[1:]
    if not rest:
        return None
    return Condition(term=rest[0], args=rest[1:], joiner=joiner, negated=negated,
                     line=line, raw=raw)


def parse_file(path: str | Path) -> TriggerFile:
    # the same file traits.parse_file reads, and read the same way: line
    # endings through untouched, so `text()` is the bytes and not a copy of
    # them with the platform's idea of a newline substituted in
    return parse_text(kb.read_text(Path(path), ENCODING))


def parse_block(text: str) -> Trigger:
    """Read ONE trigger block, as the code view's pane holds it.

    Raises :class:`TriggerError` rather than warning: a pane that edits one
    record must not quietly accept text holding two, or none.
    """
    tf = parse_text(text if text.endswith("\n") else text + "\n")
    if not tf.triggers:
        raise TriggerError("a trigger block starts with a `Trigger <name>` line — "
                           "this text has none", 1)
    if len(tf.triggers) > 1:
        raise TriggerError(
            f"this text holds {len(tf.triggers)} trigger blocks — one at a time",
            tf.triggers[1].start + 1)
    return tf.triggers[0]


# ---------------------------------------------------------------------------
# what the vocabulary can say about a parsed trigger


def unknown_terms(tf: TriggerFile) -> List[Dict]:
    """Condition terms no source has ever documented — listed, never dropped."""
    out, seen = [], set()
    for trig in tf.triggers:
        for cond in trig.conditions:
            if term_def(cond.term) or cond.term in seen:
                continue
            seen.add(cond.term)
            out.append({"term": cond.term, "trigger": trig.name,
                        "line": cond.line + 1})
    return out


def check(trig: Trigger) -> List[Dict]:
    """Conditions this trigger's event cannot answer — findings, worst first.

    A condition needs data the event has to export. ``WonBattle`` requires a
    ``character_record``; under ``SettlementTurnStart``, which exports none, it
    can never be true and the trigger silently never fires. Reading the file
    cannot show you that; this can.
    """
    ev = event_def(trig.when_to_test)
    out: List[Dict] = []
    if trig.when_to_test and ev is None:
        out.append({"kind": "unknown-event", "line": trig.wtt_line + 1,
                    "message": f"no engine event is called `{trig.when_to_test}`"})
        return out
    exports = set((ev or {}).get("exports", []))
    for cond in trig.conditions:
        d = term_def(cond.term)
        if d is None:
            out.append({"kind": "unknown-condition", "line": cond.line + 1,
                        "message": f"`{cond.term}` is not a condition anything "
                                   "documents — it may still be valid"})
            continue
        if ev is None or satisfied(d.get("requires", []), exports):
            continue
        out.append({"kind": "missing-export", "line": cond.line + 1,
                    "message": f"`{cond.term}` needs {describe(d.get('requires', []))}, "
                               f"which `{trig.when_to_test}` does not export — this "
                               "condition can never be true"})
    return out


def satisfied(requires: List[List[str]], exports) -> bool:
    """Does an event exporting ``exports`` satisfy a condition's requirements?

    ``requires`` is alternative groups — ``[[a, b], [c]]`` means (a and b) or c —
    so a condition is satisfiable when ANY group is fully exported. A condition
    that requires nothing is satisfied by everything.
    """
    if not requires:
        return True
    return any(all(t in exports for t in group) for group in requires)


def describe(requires: List[List[str]]) -> str:
    """Requirement groups as prose: ``"a and b, or c"``."""
    return ", or ".join(" and ".join(g) for g in requires) or "nothing"


# ---------------------------------------------------------------------------
# editing: splices, so untouched lines stay untouched


def _indent_of(line: str) -> str:
    return line[: len(line) - len(line.lstrip())]


def render_block(base: str, edits: Optional[Dict] = None) -> str:
    """Apply GUI edits to one trigger block and give back its text.

    ``edits`` is the save request's own shape — ``{name, when_to_test,
    conditions: [{term, args, joiner, negated}], effects: [{keyword, args}]}`` —
    and every key is optional. What is not named is not touched, right down to
    the comment banner between two clauses.
    """
    edits = edits or {}
    trig = parse_block(base)
    lines = base.split("\n")
    crlf = lines and lines[0].endswith("\r")
    lines = [ln[:-1] if ln.endswith("\r") else ln for ln in lines]

    if "name" in edits:
        name = str(edits["name"] or "").strip()
        lines[trig.start] = _sub_head(lines[trig.start], TRIGGER_KW, name)
    if "when_to_test" in edits and trig.wtt_line >= 0:
        lines[trig.wtt_line] = _sub_head(lines[trig.wtt_line], "WhenToTest",
                                         str(edits["when_to_test"] or "").strip())
    if "conditions" in edits:
        lines = _splice_conditions(lines, trig, edits["conditions"] or [])
        trig = parse_block("\n".join(lines) + "\n")
    if "effects" in edits:
        for i, e in enumerate(edits["effects"] or []):
            if i >= len(trig.effects):
                break
            eff = trig.effects[i]
            args = [str(a) for a in (e.get("args") or eff.args)]
            kw = str(e.get("keyword") or eff.keyword)
            lines[eff.line] = _keep_comment(lines[eff.line],
                                            _indent_of(lines[eff.line])
                                            + " ".join([kw] + args))
    return ("\r\n" if crlf else "\n").join(lines)


def _sub_head(line: str, keyword: str, value: str) -> str:
    """Replace a ``<keyword> <value>`` line's value, keeping indent and comment."""
    return _keep_comment(line, _indent_of(line) + keyword + (f" {value}" if value else ""))


def _keep_comment(line: str, new_code: str) -> str:
    """``new_code`` plus whatever comment the old line carried."""
    code, sep, comment = line.partition(";")
    if not sep:
        return new_code
    # keep the spacing that sat before the ';' so a column of comments stays a column
    pad = code[len(code.rstrip()):]
    return new_code + pad + ";" + comment


def _splice_conditions(lines: List[str], trig: Trigger, wanted: List[Dict]) -> List[str]:
    """Rewrite the clause lines in place; add or drop lines only where needed.

    The common edit by far is changing one operand, so a clause that has not
    changed keeps its exact line — indentation, inline comment and all. Only a
    clause that was added or removed moves anything.
    """
    old = trig.conditions
    out = list(lines)
    # A new clause joins the end of the list, so it copies the indent of the
    # clause it will sit under. These files line their `and`s up by eye and a new
    # line landing in a different column is the first thing anyone notices.
    template = _indent_of(lines[old[-1].line]) if old else "         "

    n = min(len(old), len(wanted))
    for i in range(n):
        cond, w = old[i], wanted[i]
        new = Condition(term=str(w.get("term") or cond.term),
                        args=[str(a) for a in (w.get("args") if w.get("args") is not None
                                               else cond.args)],
                        joiner=cond.joiner if i == 0 else str(
                            w.get("joiner") or cond.joiner or "and"),
                        negated=bool(w.get("negated", cond.negated)))
        if (new.term, new.args, new.joiner, new.negated) == (
                cond.term, cond.args, cond.joiner, cond.negated):
            continue                       # untouched: leave the line exactly as it is
        head = "Condition " if i == 0 else ""
        body = new.text().strip()
        code = _indent_of(lines[cond.line]) + (head + body if i == 0 else body)
        out[cond.line] = _keep_comment(lines[cond.line], code)

    if len(wanted) > len(old):             # clauses added
        extra = []
        for w in wanted[len(old):]:
            c = Condition(term=str(w.get("term") or ""),
                          args=[str(a) for a in (w.get("args") or [])],
                          joiner=str(w.get("joiner") or "and"),
                          negated=bool(w.get("negated")))
            if not c.term:
                continue
            extra.append(c.text(template))
        after = (old[-1].line if old else trig.start) + 1
        out[after:after] = extra
    elif len(wanted) < len(old):           # clauses removed
        for cond in reversed(old[len(wanted):]):
            del out[cond.line]
    return out


def new_block(t: Dict) -> str:
    """One trigger block written from scratch, in the builder's own shape.

    ``t`` is exactly what ``trgValue`` in ``web/js/triggerui.js`` produces, which
    is also what :func:`render_block` takes — so the builder, the code view and
    the save all describe a trigger the same way.
    """
    out = [f"{TRIGGER_KW} {str(t.get('name') or '').strip()}",
           f"    WhenToTest {str(t.get('when_to_test') or '').strip()}"]
    for i, c in enumerate(t.get("conditions") or []):
        clause = Condition(
            term=str(c.get("term") or ""),
            args=[str(a) for a in (c.get("args") or [])],
            joiner="" if i == 0 else str(c.get("joiner") or "and"),
            negated=bool(c.get("negated")))
        if clause.term:
            out.append(("    Condition " if i == 0 else "         ")
                       + clause.text().strip())
    for e in (t.get("effects") or []):
        args = " ".join(str(a) for a in (e.get("args") or []))
        out.append(f"    {str(e.get('keyword') or 'Affects')} {args}".rstrip())
    return "\n".join(out)


def append_block(tf: TriggerFile, block: str) -> str:
    """The file with a new trigger at the end of its trigger section.

    The engine reads triggers in order, so where one sits is a real decision;
    last is the honest default, because it is the only position that cannot
    change when an existing trigger fires.
    """
    lines = list(tf.lines)
    while lines and not lines[-1].strip():
        lines.pop()
    lines.extend([""] + [ln[:-1] if ln.endswith("\r") else ln
                         for ln in block.split("\n")])
    return tf.newline.join(lines) + (tf.newline if tf.trailing_newline else "")


def remove_block(tf: TriggerFile, trig: Trigger) -> str:
    """The file with one trigger's lines gone."""
    lines = list(tf.lines)
    del lines[trig.start:trig.end]
    return tf.newline.join(lines) + (tf.newline if tf.trailing_newline else "")


def edit_section(text: str, req: Dict, changes: List[str], warnings: List[str],
                 errors: List[str]) -> str:
    """Apply a save's trigger edits, adds and removes to a whole file's text.

    ``req`` is ``{edits: [{name, trigger|raw_block}], adds: [{trigger}],
    removes: [name]}`` — the shape both the traits and the ancillaries editors
    send, because both of them own the trigger section of their own file.

    Each change is re-parsed from the text the last one produced. A splice moves
    the lines below it, and a second edit worked out against stale line numbers
    is how an editor writes into the middle of somebody else's trigger.
    """
    for r in (req.get("removes") or []):
        name = str(r.get("name") if isinstance(r, dict) else r)
        tf = parse_text(text)
        trig = tf.get(name)
        if trig is None:
            warnings.append(f"no trigger called {name} — already gone?")
            continue
        text = remove_block(tf, trig)
        changes.append(f"- Trigger {name}")
    for e in (req.get("edits") or []):
        name = str(e.get("name") or "")
        tf = parse_text(text)
        trig = tf.get(name)
        if trig is None:
            errors.append(f"no trigger called {name}")
            continue
        base = tf.block_text(trig)
        block = (str(e["raw_block"]).strip("\r\n") if e.get("raw_block")
                 else render_block(base, e.get("trigger") or e))
        if block == base:
            continue
        text = replace_block(tf, trig, block)
        changes.append(f"~ Trigger {name}")
    for a in (req.get("adds") or []):
        tf = parse_text(text)
        t = dict(a.get("trigger") or a)
        name = str(t.get("name") or "").strip()
        if not name:
            errors.append("a new trigger needs a name")
            continue
        if tf.get(name) is not None:
            errors.append(f"{name} is already a trigger in this file")
            continue
        text = append_block(tf, new_block(t))
        changes.append(f"+ Trigger {name}")
    return text


def orphaned_by(text: str, keyword: str, name: str) -> List[str]:
    """Triggers whose every ``<keyword>`` line names ``name`` — nothing else.

    A record's name is what its own triggers point at (``Affects <trait>`` in an
    EDCT, ``AcquireAncillary <name>`` in an EDA), and one left pointing at a
    record that no longer exists is a crash. Deleting the record has to take
    these with it; a trigger that also serves other records is not in this list,
    because removing it would take theirs away too — :func:`strip_effect_lines`
    handles that half.
    """
    out = []
    for trig in parse_text(text).triggers:
        mine = [e for e in trig.effects if e.keyword == keyword and e.args]
        if mine and all(e.args[0] == name for e in mine):
            out.append(trig.name)
    return out


def strip_effect_lines(text: str, keyword: str, name: str) -> Tuple[str, int]:
    """Drop every ``<keyword> <name> …`` line, leaving its trigger standing.

    Run after the whole-trigger removals, so each line it finds belongs to a
    trigger that still serves other records: taking the trigger would take their
    points away, and leaving the line would leave the crash.
    """
    tf = parse_text(text)
    dead = sorted(e.line for t in tf.triggers for e in t.effects
                  if e.keyword == keyword and e.args and e.args[0] == name)
    if not dead:
        return text, 0
    lines = list(tf.lines)
    for i in reversed(dead):
        del lines[i]
    out = tf.newline.join(lines) + (tf.newline if tf.trailing_newline else "")
    return out, len(dead)


def replace_block(tf: TriggerFile, trig: Trigger, block: str) -> str:
    """The whole file with one trigger's lines swapped for ``block``."""
    body = block.split("\n")
    body = [ln[:-1] if ln.endswith("\r") else ln for ln in body]
    while body and not body[-1].strip():
        body.pop()
    lines = list(tf.lines)
    lines[trig.start:trig.end] = body
    out = tf.newline.join(lines)
    return out + tf.newline if tf.trailing_newline and lines else out


# ---------------------------------------------------------------------------
# spans, for the Code View widget


# ---------------------------------------------------------------------------
# what the builder's pickers are filled with


#: which vocabulary list an operand of each kind should be picked from. The
#: shapes come from the generated data, so this only has to say what a `name`
#: operand of a given term MEANS.
OPERAND_SOURCES: Dict[str, str] = {
    "Trait": "traits", "FatherTrait": "traits", "SpouseTrait": "traits",
    "FactionLeaderTrait": "traits",
    "Attribute": "attributes", "SpouseAttribute": "attributes",
    "FatherAttribute": "attributes", "FactionLeaderAttribute": "attributes",
    "HasAncType": "ancillaries", "FactionwideAncillaryExists": "ancillaries",
    "I_WorldwideAncillaryExists": "ancillaries",
    "FactionType": "factions", "CharFactionType": "factions",
    "TargetFactionType": "factions", "GeneralFoughtFaction": "factions",
    "I_LocalFaction": "factions", "I_IsFactionAIControlled": "factions",
    "CultureType": "cultures", "FactionCultureType": "cultures",
    "TargetFactionCultureType": "cultures", "GeneralFoughtCulture": "cultures",
    "SettlementBuildingExists": "buildings", "SettlementBuildingFinished": "buildings",
    "FactionBuildingExists": "buildings", "GovernorBuildingExists": "buildings",
    "BuildingFinishedByGovernor": "buildings",
}


def mod_operands(mod) -> Dict[str, List[str]]:
    """The operand lists that are a property of THIS mod, not of the engine.

    Everything here comes from a parse the toolkit already owns — trait and
    ancillary names off the same pass that read the triggers, factions and
    cultures from the buildings layer, building levels from the EDB. Nothing is
    re-parsed, and nothing is hardcoded per mod.
    """
    out: Dict[str, List[str]] = {"traits": [], "ancillaries": [], "factions": [],
                                 "cultures": [], "buildings": []}
    if mod is None:
        return out
    for attr, keyword, key in (("edct_path", "Trait", "traits"),
                               ("eda_path", "Ancillary", "ancillaries")):
        path = getattr(mod, attr, None)
        if path is None or not path.exists():
            continue
        try:
            tf = parse_file(path)
        except OSError:
            continue
        out[key] = sorted(set(tf.definitions.get(keyword, [])))
    try:
        out["factions"] = sorted(mod.faction_cultures)
        out["cultures"] = sorted(set(mod.faction_cultures.values()))
    except (OSError, ValueError):
        pass
    try:
        levels = []
        for bl in mod.edb.buildings:
            levels.append(bl.name)
            levels.extend(b.name for b in bl.blocks)
        out["buildings"] = sorted(set(levels))
    except (OSError, ValueError, AttributeError):
        pass
    return out


def vocab_payload(mod=None) -> Dict:
    """Everything the trigger builder needs: the engine's vocabulary + this mod's.

    The engine half is the generated file, identical for every mod. The mod half
    is what its own traits, ancillaries, factions, cultures and buildings are
    called, so a picker offers names that exist here rather than vanilla's.
    """
    v = vocab()
    return {
        "conditions": v.get("conditions", []),
        "events": v.get("events", []),
        "operators": v.get("operators", list(OPS)),
        "attributes": v.get("attributes", []),
        "operand_sources": OPERAND_SOURCES,
        "operands": dict(mod_operands(mod), attributes=v.get("attributes", [])),
        "source": v.get("source", {}),
        "mod": getattr(mod, "name", ""),
    }


def block_spans(block: str) -> Dict[str, List[List[int]]]:
    """``{label: [[first, last]]}``, 1-based, for one trigger block."""
    trig = parse_block(block if block.endswith("\n") else block + "\n")
    spans: Dict[str, List[List[int]]] = {"name": [[trig.start + 1, trig.start + 1]]}
    if trig.wtt_line >= 0:
        spans["when_to_test"] = [[trig.wtt_line + 1, trig.wtt_line + 1]]
    for i, c in enumerate(trig.conditions):
        spans[f"condition#{i + 1}"] = [[c.line + 1, c.line + 1]]
    for i, e in enumerate(trig.effects):
        spans[f"effect#{i + 1}"] = [[e.line + 1, e.line + 1]]
    return spans


def block_fields(block: str) -> List[Tuple[str, str]]:
    """``[(label, value)]`` for one block, in the order the lines appear."""
    trig = parse_block(block if block.endswith("\n") else block + "\n")
    out = [("name", trig.name)]
    if trig.wtt_line >= 0:
        out.append(("when_to_test", trig.when_to_test))
    for i, c in enumerate(trig.conditions):
        out.append((f"condition#{i + 1}", c.text().strip()))
    for i, e in enumerate(trig.effects):
        out.append((f"effect#{i + 1}", " ".join([e.keyword] + e.args)))
    return out
